### ISSUE TITLE
css布局问题？css实现三列布局怎么做？如果中间是自适应又怎么做？

### ISSUE THREAD

**Issue by LDY0725** [LDY0725/Study-Notes#17]
## css布局问题？css实现三列布局怎么做？如果中间是自适应又怎么做？
- 流体布局 --- 缺点是主要内容无法最先加载，当页面内容较多时会影响用户体验。
  ```CSS
  .left {
      width: 100px;
      height: 200px;
	    background-color: red;
      float: left;
	}
	.right {
	    width: 200px;
	    height: 200px;
	    background-color: blue;
	    float: right;
	}
	.main {
	    margin-left: 100px;
	    margin-right: 200px;
	    height: 200px;
	    background-color: green;
	}
  ```

  ```HTML
  <div class="container">
      <div class="left"></div>
      <div class="right"></div>
      <div class="main"></div>
  </div>
  ```
-  BFC 三栏布局 ---- 缺点是主要内容模块无法最先加载，当页面中内容较多时会影响用户体验。因此为了解决这个问题，有了下面要介绍的布局方案双飞翼布局。
  ```CSS
  .left {
      float: left;
      height: 200px;
      width: 100px;
      background-color: red;
  }
  .right {
      width: 200px;
      height: 200px;
      float: right;
      background-color: blue;
  }
  .main {
      height: 200px;
      overflow: hidden;
      background-color: green;
  }
  ```
  ```HTML
  <div class="container">
      <div class="left"></div>
      <div class="right"></div>
      <div class="main"></div>
  </div>
  ```
- 双飞翼布局 --- 主体内容可以优先加载，HTML 代码结构稍微复杂点。
  ```CSS
  .content {
    float: left;
    width: 100%;
  }
  .main {
    height: 200px;
    margin-left: 100px;
    margin-right: 200px;
    background-color: green;
  }
  .left {
    float: left;
    height: 200px;
    width: 100px;
    margin-left: -100%;
    background-color: red;
  }
  .right {
    width: 200px;
    height: 200px;
    float: right;
    margin-left: -200px;
    background-color: blue;
  }
  ```
  ``` HTML
  <div class="content">
    <div class="main"></div>
  </div>
  <div class="left"></div>
  <div class="right"></div>
  ```
- 圣杯布局 ----- 相对于双飞翼布局来说，HTML 结构相对简单，但是样式定义就稍微复杂，也是优先加载内容主体。
  ```CSS
  .container {
      margin-left: 100px;
      margin-right: 200px;
  }
  .main {
      float: left;
      width: 100%;
      height: 200px;
      background-color: green;
  }
  .left {
      position: relative;
      left: 100px;
      float: left;
      width: 100px;
      height: 200px;
      margin-left: -100%;
      background-color: red;
  }
  .right {
      position: relative;
      left: 100px;
      float: left;
      width: 200px;
      height: 200px;
      margin-left: -200px;
      background-color: blue;
  }
  ```
  ```HTML
  <div class="container">
   <div class="main"></div>
   <div class="left"></div>
   <div class="right"></div>
  </div>
  ```  
- Flex 布局 ----- 简单实用，未来的趋势，需要考虑浏览器的兼容性
  ```CSS
  .container {
      display: flex;
  }
  .main {
      flex-grow: 1;
      height: 200px;
      background-color: red;
  }
  .left {
      order: -1;
      flex-grow: 0;
      flex-shrink: 1;   //属性定义了项目的缩小比例，默认为1，即如果空间不足，该项目将缩小
      flex-basis: 200px;  //属性定义了在分配多余空间之前，项目占据的主轴空间（main size）。浏览器根据这个属性，计算主轴是否有多余空间。它的默认值为auto，即项目的本来大小
      height: 200px;
      background-color: blue;
  }
  .right {
      flex-grow: 0;
      flex-shrink: 1;
      flex-basis: 100px;
      height: 200px;
      background-color: green;
  }
  ```
  ```HTML
  <div class="container">
   <div class="main"></div>
   <div class="left"></div>
   <div class="right"></div>
  </div>
  ```
