### ISSUE TITLE
CSS如何实现居中&隐藏元素

### ISSUE THREAD

**Issue by LDY0725** [LDY0725/Study-Notes#19]
#### CSS如何实现居中
- flex 居中
```CSS
.container {
    display: flex;
    align-items: center;
}  
.main {}
```
```HTML
<div class="container">
    <div class="main"></div>
</div>
```

- margin 居中
```CSS
.container {}  
.main {
    margin: 0 auto;
    text-align: center
}
```
```HTML
<div class="container">
    <div class="main"></div>
</div>
```
- 父子元素宽度已知
  - display:table-cell和margin-left 居中,position:absolute。

---
#### CSS如何隐藏元素
- opacity 设为 0：是设置一个元素的透明度。它不是为改变元素的边界框（bounding box）而设计的。这意味着将 opacity 设为 0 只能从视觉上隐藏元素。而元素本身依然占据它自己的位置并对网页的布局起作用。它也将响应用户交互。
- visibility 设为 hidden：如同 opacity 属性，被隐藏的元素依然会对我们的网页布局起作用。与 opacity 唯一不同的是它不会响应任何用户交互。此外，元素在读屏软件中也会被隐藏。
- display 设为 none： none 确保元素不可见并且连盒模型也不生成。使用这个属性，被隐藏的元素不占据任何空间。不仅如此，一旦 display 设为 none 任何对该元素直接打用户交互操作都不可能生效。此外，读屏软件也不会读到元素的内容。这种方式产生的效果就像元素完全不存在。
- position 设为 absolute 然后将位置设到不可见区域。
