### ISSUE TITLE
CSS基本问题（三）

### ISSUE THREAD

**Issue by LDY0725** [LDY0725/Study-Notes#32]
#### 实现两栏布局有哪些方法？
-
  ```CSS
  .left {
    width: 100px;
    height: 200px;
    background-color: red;
    float: left;
  }
  .main {
    height: 200px;
    background-color: green;
    overflow: auto;
  }
  ```
  ```HTML
  <div class="container">
    <div class="left"></div>
    <div class="main"></div>
  </div>
  ```
-
  ```CSS
  .left {
    width: 100px;
    height: 200px;
    background-color: red;
    float: left;
    margin-left: -100%;
  }
  .main {
    height: 200px;
    background-color: green;
    margin-left: 100px;
  }
  .father {
    float: left;
    width: 100%;
  }
  ```
  ```HTML
  <div class="container">
    <div class="father">
      <div class="main"></div>
    </div>
    <div class="left"></div>
  </div>
  ```

---
#### 流式布局如何实现，响应式布局如何实现
- 百分比布局，也叫流式布局
- 响应式网页布局:三种技术（弹性网格布局，弹性图片，媒体和媒体查询）：针对任意设备对网页内容进行布局的一种显示机制。

---
#### overflow:hidden有什么缺点？
有的时候会失效，position：absolute；

---
#### padding百分比是相对于父级宽度还是自身的宽度
margin,padding的百分比竟然是相对与父元素的宽度来进行计算了

---
#### css3动画，transition和animation的区别，animation的属性.
- transition 是令一个或多个可以用数值表示的css属性值发生变化时产生过渡效果。
- animation 则是属于关键帧动画的范畴，它本身被用来替代一些纯粹表现的javascript代码而实现动画。基于animation和@keyframe 的动画一方面也是为了实现表现与行为的分离，另一方面也使得前端设计师可以专注得进行动画开发而不是冗余的代码中。同时，它还应该被用来提高动画的渲染性能，当然，渲染性能这是浏览器的事情，目前看来，三大主流内核的animation/@keyframe的性能都不算高。webkit甚至在元素被transform矩阵变化并脱离文档流后在某些伪类选择器里应用还会有bug。

##### animation的属性
- animation-name:规定需要绑定到选择器的 keyframe 名称。。
- animation-duration:规定完成动画所花费的时间，以秒或毫秒计。
- animation-timing-function：规定动画的速度曲线。
- animation-delay：规定在动画开始之前的延迟。
- animation-iteration-count：规定动画应该播放的次数。
- animation-direction：规定是否应该轮流反向播放动画。

---
#### CSS 3 如何实现旋转图片（transform: rotate）

[CSS3 3D transform](http://www.zhangxinxu.com/wordpress/2012/09/css3-3d-transform-perspective-animate-transition/)

---
##### 浮动元素引起的问题和解决办法？
- 父级div手动定义height
- 结尾处加空div标签 clear:both
- 父级div定义 伪类:after 和 zoom
- 父级div定义 overflow:hidden ,必须定义width或zoom:1，同时不能定义height，
- 父级div定义 overflow:auto 必须定义width或zoom:1，同时不能定义height (不推荐)
- 父级div 也一起浮动 (不推荐)
- 父级div定义 display:table (不推荐)
- 父级div定义 display:table (不推荐)

##### 元素浮动后的display值
block
